### ISSUE TITLE
How to resolve this issue 'JWT must consist of Header, Payload, and Signature'

### ISSUE THREAD

**Issue by JKAngular** [P-oke/SocialAuthentication#4]
Hi

How to resolve this issue
Google.Apis.Auth.InvalidJwtException: 'JWT must consist of Header, Payload, and Signature'

**Comment by P-oke** [comment]
Hi @JKAngular 

Please could you confirm you're sending a valid id token (JWT) issued from Google Oauth server to the _GoogleSignIn_ endpoint and also ensure you're using a valid ClientId and Client Secret issued from Google developer console when creating a project.
